version: 2.1
orbs:
  gradle: circleci/gradle@2.2.0
workflows:
  default:
    jobs:
      - build-styles
      - deploy:
          requires:
            - build-styles
          filters:
            branches:
              only:
                - gh-pages

jobs:
  build-styles:
    docker:
      - image: cimg/node:17.1.0
    resource_class: small
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update
      - run:
          name: "Install Dependencies"
          command: npm install
      - run:
          name: "Setup Artifacts Folder"
          command: |
            mkdir ~/working
            mkdir ~/working/font-glyphs
      - run:
          name: "Copy Glyphs"
          command: |
            cp -r ./font-glyphs/* ~/working/
      - run:
          name: "Generate sprites"
          command: |
            ./tools/generate_sprite_sheets
      - run:
          name: "Add Files"
          command: |
            cp sprites*.json ~/working/
            cp sprites*.png ~/working/
            cp style.json ~/working/
            cp map.html ~/working/
      - run:
          name: "Packing Artifact"
          command: |
            mkdir ~/artifacts
            tar cfvz ~/artifacts/styles.tar.gz ~/working/*
      - persist_to_workspace:
          root: ~/artifacts
          paths:
            - styles.tar.gz

  deploy:
    docker:
      - image: cimg/base:2021.11
    resource_class: small
    steps:
      - attach_workspace:
          at: ~/artifacts
      - add_ssh_keys:
          fingerprints:
            - "5e:b9:08:4e:01:f0:71:3c:74:0c:d9:10:3b:6d:74:de"
      - run:
          name: "SSH Upload"
          command: |
            sudo ssh-keyscan -H maps.tuerantuer.org >> known_hosts
            scp -o UserKnownHostsFile=known_hosts ~/artifacts/styles.tar.gz ci@maps.tuerantuer.org:/var/www/styles/ehrenamtskarte-styles.tar.gz
            ssh -o UserKnownHostsFile=known_hosts ci@maps.tuerantuer.org \<<SSH
              mkdir -p /var/www/styles/ehrenamtskarte
              cd /var/www/styles/ehrenamtskarte
              tar xfv /var/www/styles/ehrenamtskarte-styles.tar.gz
              rm /var/www/styles/ehrenamtskarte-styles.tar.gz
            SSH
