name: Build sprites
on:
  push:
    branches: [ gh-pages ]
    paths: [ svgs/** ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: CheckouÔ∏èt
        uses: actions/checkout@v4.1.2
        
      - name: Setup node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20

      - name: Build
        run: |
          npm ci
          npm run build_sprites

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          target-folder: sprites
          folder: /home/runner/work/osm-liberty/osm-liberty/sprites
          git-config-name: maputnik-bot
          git-config-email: <>
          commit-message: Build sprites
